[workspace]
members = ["stdgeo-cli", "stdgeo-lib"]
resolver = "2"

# Workspace profiles apply to all members of the workspace
[profile.release]
strip = true             # Remove debug symbols
opt-level = "z"          # Optimize for size
lto = true               # Link-time optimization
codegen-units = 1        # Better optimization
panic = "abort"          # Don't include unwinding code
overflow-checks = false
debug = false

